### ISSUE TITLE
firmware hang after/during charge ?

### ISSUE THREAD

**Issue by ChrisVeigl** [magicshifter/MS3000#7] opened 2016-03-24 16:08 UTC
after the battery was discharged to a point where i could not start the device anymore
i attached a 5V supply to the USB-port of the MS3000 to supply charge.

after several hours  i noticed 2 leds showing green (i thought this indicated full charge)
I removed the power supply but the device was in a undetermined state (i could not activate any of the modes, the 2 green leds stayed on - I had to press the reset button ...)

maybe related: during charge i tried to turn the device on but it didnt come up (maybe because the battery level was still below threshold)

**Comment by seclorum** [comment] 2016-03-25 13:34
I have not been able to replicate this - were you perhaps flashing firmware in the session prior to running the battery down?

TODO: add extreme low-power check on boot-up.

**Comment by ChrisVeigl** [comment] 2016-03-25 15:10
I have also problems replicating that problem ... (the question is if this is a good or a bad sign ;-)
I did not flash firmware before the issue happened.

**Comment by wizard23** [comment] 2016-03-25 15:14
Wild guess: the seral port was opened and the RST and DTR lines got changed so it reset into bootloader mode. You SHOULD be able to reset it again in this state by pressing the button thats furthest away from the USB connector (just press every one of the 3 buttons if you are unsure which). But this will only work if the USB port is not connected or at least not opened with the RTS/DTR line. Do you habve any automated task that opens serial connections on your machine? There was an ubuntu version for examplre that had a braile package that opened every USBserial port it found because it thought tthis was the braile device it was looking for. This has been fixed but if you connected the USB port to a PC thats one posibility. 

Does this help in reproducing the bug?

if that was the problem a usb charger obnly (without PC) should solve this.

**Comment by wizard23** [comment] 2016-03-25 15:15
if it's the low power that would make it harder to replicate for you but we could try with a power supply.

**Comment by ChrisVeigl** [comment] 2016-03-25 15:36
@serial port: i used a USB charger so that can't be the reason. 
testing with an external supply is a good idea. 
the problem seems to occur very rarely though - maybe not a big issue... however an info how to reset the device might be useful in the user manual (if it's not alredy there ;)

**Comment by seclorum** [comment] 2016-06-20 07:04
We recently addressed an issue with the firmware not detecting button-presses, which would induce the condition of 'hanged firmware' as you describe.  Please update to the latest firmware release and re-test in relation to this issue:

http://github.com/magicshifter/MS3000/releases/latest/

**Comment by wizard23** [comment] 2016-09-08 02:10
this was fixed in Firmware version 1.2
https://github.com/magicshifter/MS3000/wiki/FirmwareUpdate

**Closed as completed by wizard23** 2016-09-08 02:10 UTC
